insert or ignore into continent (continent_name) values ('Europe')
insert or ignore into continent (continent_name) values ('Asia')
insert or ignore into continent (continent_name) values ('North America')
insert or ignore into continent (continent_name) values ('South America')
insert or ignore into continent (continent_name) values ('Africa')
insert or ignore into continent (continent_name) values ('Antarctica')
insert or ignore into continent (continent_name) values ('Australia')