insert or ignore into position (position_short_name, position_long_name) values ('GK', 'Goalkeeper')
insert or ignore into position (position_short_name, position_long_name) values ('RWB', 'Right Wing Back')
insert or ignore into position (position_short_name, position_long_name) values ('RB', 'Right Back')
insert or ignore into position (position_short_name, position_long_name) values ('CB', 'Centre Back')
insert or ignore into position (position_short_name, position_long_name) values ('LB', 'Left Back')
insert or ignore into position (position_short_name, position_long_name) values ('LWB', 'Left Wing Back')
insert or ignore into position (position_short_name, position_long_name) values ('CDM', 'Central Defensive Midfielder')
insert or ignore into position (position_short_name, position_long_name) values ('RM', 'Right Midfielder')
insert or ignore into position (position_short_name, position_long_name) values ('LM', 'Left Midfielder')
insert or ignore into position (position_short_name, position_long_name) values ('CM', 'Central Midfielder')
insert or ignore into position (position_short_name, position_long_name) values ('CAM', 'Central Attacking Midfielder')
insert or ignore into position (position_short_name, position_long_name) values ('RW', 'Right Wing')
insert or ignore into position (position_short_name, position_long_name) values ('LW', 'Left Wing')
insert or ignore into position (position_short_name, position_long_name) values ('CF', 'Centre Forward')
insert or ignore into position (position_short_name, position_long_name) values ('RF', 'Right Forward')
insert or ignore into position (position_short_name, position_long_name) values ('LF', 'Left Forward')
insert or ignore into position (position_short_name, position_long_name) values ('ST', 'Striker')